name: BUILD

on:
  push:
  schedule:
    - cron:  '1 */8 * * *'
  workflow_dispatch:

jobs:
  buildAUR:
    strategy:
      matrix:
        repos: [osu-lazer, weechat-notify-send, fpp, redsocks, git-cola, realesrgan-ncnn-vulkan, python-torchaudio, python-torchinfo, python-rapidocr-onnxruntime, darkly, python-faster-whisper, code-git, visual-studio-code-insiders-bin, visual-studio-code-bin]
        include:
          - repos: git-cola
            preinstall-pkgs: "at-spi2-core"
          - repos: realesrgan-ncnn-vulkan
            preinstall-pkgs: "vulkan-intel"

      fail-fast: false
      
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - uses: ./build-aur-action
      with:
        repo-name: ${{ matrix.repos }}
        preinstallPkgs: ${{ matrix.preinstall-pkgs }}
    
    - uses: actions/upload-artifact@v4
      with:
        path: ./*/*.pkg.tar.zst
        name: ${{ matrix.repos }}
        if-no-files-found: error
        
    - uses: softprops/action-gh-release@v2
      with:
        allowUpdates: true
        tag: "packages"
        files: "./*/*.zst"
